#!/bin/sh

########################################
### expect_for_LOTUS.sh
### Naoki Umeda 2022 at Osaka University
########################################

echo "#!/bin/sh"
echo ""
echo "#################################################"
echo "### This file is generated by expect_for_LOTUS.sh"
echo "### `date "+%Y-%m-%d %H:%M:%S"`"
echo "#################################################"
echo ""

echo "expect -c \""
echo "set timeout -1"
echo "spawn python3 main.py"

while read line
do
  echo expect \\\"LOTUS \>\> \\\"
  echo send \\\"${line}\\\\n\\\"
done

echo expect \\\"LOTUS \>\> \\\"
echo "send exit"
echo "exit 0"
echo "\""
