#!/bin/sh

#################################################
### This file is generated by expect_for_LOTUS.sh
### 2022-05-03 18:48:46
#################################################

expect -c "
set timeout -1
spawn python3 ../main.py
expect \"LOTUS >> \"
send \"addAS 1\n\"
expect \"LOTUS >> \"
send \"addAS 10\n\"
expect \"LOTUS >> \"
send \"addAS 11\n\"
expect \"LOTUS >> \"
send \"addAS 12\n\"
expect \"LOTUS >> \"
send \"addAS 100\n\"
expect \"LOTUS >> \"
send \"addAS 200\n\"
expect \"LOTUS >> \"
send \"addConnection down 1 10\n\"
expect \"LOTUS >> \"
send \"addConnection down 10 100\n\"
expect \"LOTUS >> \"
send \"addConnection down 10 200\n\"
expect \"LOTUS >> \"
send \"addConnection peer 10 11\n\"
expect \"LOTUS >> \"
send \"addConnection peer 11 12\n\"
expect \"LOTUS >> \"
send \"autoASPA 100 1\n\"
expect \"LOTUS >> \"
send \"setASPV 1 on 1\n\"
expect \"LOTUS >> \"
send \"setASPV 1 on 1\n\"
expect \"LOTUS >> \"
send \"addAllASInit\n\"
expect \"LOTUS >> \"
send \"run\n\"
expect \"LOTUS >> \"
send \"showASList\n\"
expect \"LOTUS >> \"
send exit
exit 0
"
